# Tree Maker compilation MakeFile

CC = gcc
CFLAGS = -Wall -Wextra -Werror -I $(INCLUDES)
EXEC = bin/TreeMaker.exe
OBJ = $(SRC:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o) 
OBJ_DIR = bin/obj
INCLUDES = includes
SRC_DIR = src
SRC  = $(wildcard $(SRC_DIR)/*.c)

all: $(EXEC)

exec: $(EXEC)
	./$(EXEC)

$(OBJ): $(SRC)
	$(CC) -c $< -o $@

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) -o $(EXEC) $(OBJ)