# Tree Maker compilation MakeFile

CC = gcc
CFLAGS = -Wall -Wextra -Werror -I $(INCLUDES)
EXEC = bin/TreeMaker.exe
INCLUDES = includes
SRC_DIR = src
SRC  = $(wildcard $(SRC_DIR)/*.c)

all: $(EXEC)

exec: $(EXEC)
	bin/$(EXEC) tests/tree_test.txt

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) -o $(EXEC) $(SRC)